### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by Uippao** [FoxWorn3365/UncomplicatedCustomRoles#2]
I configured it according to the instructions, yet the plugin doesn´t seem to care one bit about what I write into the config file. I don´t know if it´s a bug or just me doing something wrong. Can you help me?

**Comment by Uippao** [comment]
Thank you for the response, though I got it working myself(it turned out to
be my mistake). I am not extremely surprised about it, I sometimes miss
something extremely obvious.

ma 6. marrask. 2023 klo 19.08 FoxWorn3365 ***@***.***>
kirjoitti:

**Comment by FoxWorn3365** [comment]
Happy to see that.
Thank you for using UCR and sorry for the incredible delayed response, sadly GitHub Mail notifications doesn't work well for me.
