### ISSUE TITLE
Problem with broadcast and inventory.

### ISSUE THREAD

**Issue by DANIEL22354** [FoxWorn3365/UncomplicatedCustomRoles#6]
I’ve been doing this all day and still don’t understand what the error is. The problem is that no matter how I change the broadcast text, nothing changes, only the spawn chance and effects change, and I also can’t output anything to the inventory even though I’m writing a debug ID items...
P.S. I’m from Russia, so first I tried to write a description and name for the broadcast in Cyrillic, but nothing worked, then I wrote it in English, but that didn’t work either.
My custom_roles text:
  custom_roles:
  - id: 1
    name: 'Уборщик'
    custom_info: 'Сохраняйте чистоту в комплексе.'
    spawn_condition: RoundStart
    max_players: 2
    min_players: 1
    spawn_chance: 60
    role: ClassD
    role_appearance: ClassD
    can_replace_roles:
    - ClassD
    health: 100
    max_health: 100
    ahp: 0
    hume_shield: 0
    movement_boost: 0
    effects:
    - effect_type: Scp207
      duration: 0
      intensity: 0
    can_escape: true
    scale:
      x: 0
      y: 0
      z: 0
    spawn_broadcast: |-
      Вы <color=orange><b>Уборщик</b></color>!
      Сохраняйте чистоту в комплексе!
    spawn_broadcast_duration: 5
    inventory:
    - Flashlight
    - KeycardJanitor
    - Medkit
    custom_items_inventory: []
    ammo:
      Nato9: 0
    spawn: RoomsSpawn
    spawn_zones: []
    spawn_rooms:
    - LczToilets
    spawn_position:
      x: 0
      y: 0
      z: 0
    spawn_offset:
      x: 0
      y: 0
      z: 0
    ignore_spawn_system: false

**Comment by FoxWorn3365** [comment]
Is there any YAML error in the console?

**Comment by DANIEL22354** [comment]
> Is there any YAML error in the console?

I found the problem. I had an old Exiled...
In any case, thanks to those who tried to help)
