### ISSUE TITLE
config gets deleted and every class is gone except the example janitor role

### ISSUE THREAD

**Issue by tinyengine1** [FoxWorn3365/UncomplicatedCustomRoles#7]
I wrote some custom roles so i restarted the server however the roles still werent in the game so i checked the config again and everything was gone and put into the config.yml.old file.
Happens at every restart theres just the janitor role

**Comment by DANIEL22354** [comment]
the same

**Comment by FoxWorn3365** [comment]
This happens when there's a mistake in the YAML syntax / types for values and EXILED resets the config.
There must be an error in the console btw

**Comment by tinyengine1** [comment]
I found the error. Hovewer there doesn't seem to be any errors with the yaml file.

[ERROR] [Exiled.Loader] UncomplicatedCustomRoles configs could not be loaded, some of them are in a wrong format, default configs will be loaded instead!

**Comment by tinyengine1** [comment]
Here's my config
https://hastebin.skyra.pw/yobobireku.nestedtext

**Comment by DANIEL22354** [comment]
could this be due to Synapse?

**Comment by tinyengine1** [comment]
> could this be due to Synapse?

I don't see how synapsw would be the issue

**Comment by FoxWorn3365** [comment]
> Here's my config https://hastebin.skyra.pw/yobobireku.nestedtext

Can you send also the error?
Thanks!

**Comment by DANIEL22354** [comment]
> > Here's my config https://hastebin.skyra.pw/yobobireku.nestedtext
> 
> Can you send also the error? Thanks!

I found the problem. I had an old Exiled...
In any case, thanks to those who tried to help)

**Comment by FoxWorn3365** [comment]
Oh, perfect!
You're welcome
