### ISSUE TITLE
Plugin Serpents Hand Conflict With UncomplicatedRoles

### ISSUE THREAD

**Issue by DANIEL22354** [FoxWorn3365/UncomplicatedCustomRoles#8]
I noticed that when I add the Serpent's Hand plugin,it starts to conflict with the UncomplicatedRoles plugin.I hope I helped save someone some time.

**Comment by FoxWorn3365** [comment]
You're too generic, can you explain better?
And also send things like logs, screen and so on?
It would help

**Comment by DANIEL22354** [comment]
> You're too generic, can you explain better? And also send things like logs, screen and so on? It would help

To be more specific, the Serpents Hand plugin not only conflicts with UncomplicatedRoles, but also breaks Exiled because after installing it, a lot of YAML-related errors appear in the console

**Comment by DANIEL22354** [comment]
I tried deleting it but it didn’t help, so I decided to completely reinstall Exiled without adding this plugin and everything worked

**Comment by DANIEL22354** [comment]
But I noticed that if we talk about the new version of UncomplicatedRoles, there are no errors)!

**Comment by DANIEL22354** [comment]
But still I’m not sure that the Serpents Hand plugin is completely working.

**Comment by FoxWorn3365** [comment]
Probably it's not working, you should open an Issue on their repo, not here

**Comment by DANIEL22354** [comment]
> Probably it's not working, you should open an Issue on their repo, not here

Okay
