### ISSUE TITLE
Spawn CustomRole with a wave of MTF or Chaos Insurgency.

### ISSUE THREAD

**Issue by DANIEL22354** [FoxWorn3365/UncomplicatedCustomRoles#9]
Sorry for the stupid question,but how can I now make the role spawn with MTF or Chaos Insurgency?
It’s just that earlier it was written in the documentation,but now it’s not.
And yes,sorry for asking a lot of questions lately.
I tried to do this via can_replace_roles,but it didn't work.

My config:
https://hastebin.com/share/naqonibiju.yaml

**Comment by Lyxysx** [comment]
Use instead of roomspawn change it with KeepRoleSpawn

**Comment by DANIEL22354** [comment]
> Use instead of roomspawn change it with KeepRoleSpawn

Hello, this is not working... I spawn as MTF Captain or other MTF classes, but not as OBR.

**Comment by FoxWorn3365** [comment]
You should use the `can_replace_roles` correctly

**Comment by FoxWorn3365** [comment]
fixed
